### ISSUE TITLE
[Question] 一些样式改善

### ISSUE THREAD

**Issue by Crystal-RainSlide** [FirefoxBar/HeaderEditor#161]
### 在一些输入框中使用等宽字体

``` CSS
{
	font-family: monospace;
}
```

输入框具体有：

- 匹配类型为正则表达式时的匹配规则、排除规则和重定向至 `#rule-matchRule, #rule-excludeRule, #rule-redirectTo`；
- 修改请求头、修改响应头的头名称和头内容；
- 自定义函数代码框 `#rule-code`；

### 调整自定义函数代码框的高度限制

vue-material 引入的代码：

``` CSS
.md-field .md-textarea {
	min-height: 32px;
	max-height: 230px;
	padding: 5px 0;
	resize: none;
	line-height: 1.3em;
}
```

顶栏高 64px，剩下的空间都可以展示代码框：

``` CSS
.md-field .md-textarea {
	max-height: calc(100vh - 64px);
}
```

### 调大一些小于 14px 的文本

``` CSS
.md-tooltip,
.md-tabs-navigation .md-button,
.md-table-head {
	font-size: inherit;
}
```
